### ISSUE TITLE
ارور 500 گرفتن توکن

### ISSUE THREAD

**Issue by xSerioUsx78** [thisiskarimi/moadian#1]
سلام وقت بخیر
ماژول شما تست شده ؟ کاملا درست کار میکنه برای گرفتن توکن و بقیه چیزها؟
چون بنده کدش رو نوشته بودم و ارور 500 میگیرم و کتالخانه شما رو هم تست کردم باز هم ارور 500 میگیرم.

**Comment by thisiskarimi** [comment]
سلام خدمت شما
بله پکیج به خوبی در حال کار هستش و صورتحساب ها به سامانه ارسال شدند.
در صورت تمایل کدتون رو در تلگرام ارسال کنید تا راهنماییتون کنم.

**Comment by thisiskarimi** [comment]
طبق گفته دوستمون با سوییچ از سیستم عامل ویندوز به لینوکس(توزیع اوبونتو) مشکل حل شد و صورتحساب به درستی ارسال شد اما قطعا این راه حل اصلی نمیباشد.
