### ISSUE TITLE
استعلام صورتحساب ها

### ISSUE THREAD

**Issue by nimbolism** [thisiskarimi/moadian#2]
سلام خسته نباشید، من هرچی بسته میفرستم به کمک کد شما کد `5205` ارور میخوره
به سامانه خودشون که `58167000` هست زنگ زدم و پرسیدم لیست خطاهارو بهم اینارو گفتن:

```
4205 مشکل در ارسال aes
4206 داده ها معتبر نیستند برای رمزگشایی
4207 اشتباه است aes
4208 داده ها با کلید متقارن رمزگذاری نشدند
4209 کد اقتصادی
42109 بسته کد اقتصادی معتبر نیست
4211-4212 امضا مشکل دارد
5200: گفتند این گروه مربوط به احراز می باشد
```

که خب یعنی این خطا جزو مورد آخری است..
بنده خودم هم به زبان GO این برنامه رو نوشتم و ارور های مختلفی گرفتم تا الان از جمله `5203`، `5205` و کد `4208` که الان دارم دریافت می کنم ولی نتونستم این مشکل هارو حل کنم تا به امروز
فرق اساسی ای که کد من با شما داره اختلاف سایز عجیب صورتحساب رمز شده هست
برای مثال
خروجی PHP شما:
```tC6dXotRA1BOAqnuu446TKF/4skxv6Y=```
ولی خروجی دیتای من حتی با اینکه همه چی از جمله سایز های iv و aes یکسان است اما:
```JbvQl5hiCFs8E1+hzWSVOEN6/15/sNllLXKnJgymTNbLbYvSgo+lqTumhDBlulRbphIESlYukrrt58eE11QMIz8KI986qIlq/n43zjr44WV3XTqyoP82xZPg99p+J0OiMziMoYxSRLoPYOibQg5C/LK267oguqnhHgPyDULTb0TX/HQe+OjSxhHT+U7A+zmOyP5jGg+BUa7mOs+HR6iSAxwcYQ07n182BgAAcv6ihh4P2ad2PEZ3eSdqplrPj0dJi4eWWypTaQSbO6tLMXYR4vpz/TfzxBK+kgf3GIOyOYvIAN7Xmq6BBGvFu8mcDxbLC3cngkwxnSo6bu3y99JVWltuPGdpGqC4kfj8930Vp8q5B9tXYfTzkjdRJlvKgKVE3KLaRaOt9RcOxrvxgaP7fFdl49InZK3+GeOaGAMCzql3kRSyk5xwuH1RYr94k/43xyxmIzfSy6x3Grj/DQFlvIR28vtmQ8Rxj7xze7KmbXqw/2iKyggwMmqyz40sWOFfJQtQkJOwPZVUfDIgyA2UlR2Q3eM0HS7E0Po7GqqrTHKNrSHyVlQqhgTB6XXefz6YfNj11h3RSlQriIw5QxXFQdyRajLGlj4wJPzajZKCYE5t8pa3EyypLAJIDLXGhQ9NrUQwewO5Kb1frH3DR2RoivrGvN+K+xFjXjlgmwgcJEjAz7SeDsGbqOzl3eSUGVxCxH1T2u8cSdsxdBYDlPs89mxinuX3ZyN6KzLaenMZX5QGWwwPYmMSL2/yK6oBgtUYt16BDaSLM7m7YvjMtLne6xHcskzXI7wwc/CvvR/o5V1ECITCTkoqbK7GtHoL1uMhrmKYBfoVjp+uTBfTtprHxhErENcaPhM+82DlwhT8xLrHd/H9GMpS7xCo2KIc3buo+GqG+YAt3/84QTNGJh1cQRLkcUjo0NuV8g/HfYdXzQE6Z3sRYWbH8zI6nf2pD4jW3lyeCVntN+3egnKwnHx3WhbJFx+QPMa7EBKK2bf4YTNK85S2yknUD8V0oi+OAcXK3MLTt/G6HoRiJm/X9fBEfhMV8BiiH3XU2WowZEgrHlhvPN80qrQDBtMQjAYrTXhXQ5V9ovKubWKfa1m2Af8/UszXtTWFaMSeIcHSp3Gu+jhhi0Xl7aEeKwj1/fM3j18OGIBPwhJh0Ogx3AtqSjrYIko6eY2mCKWSzB//KvAu7MKXSntX8IqPbt3YiDcLPBkFjHwkDvEAD06LicUhtxxZNvmVYprHnnqoA3f27tGeReYypsiXTZIF6J2DwrXf6+4m1skxr5sTMfUJRqmaxPe7RHUqUjqvJWsQlls1WNQArVNd3JuUzBcvi2I3IF649rwjdzoJG6yRUIF/umB6I4Jb89iVz6nTLIyDCanoC2iNj6Io9SGdGJE/5xjSMLJHqhx5/YSJTEhkfoina/Zr95hSooX4/YXo7y8ZFul9SVEOGddDIuiH4BnlI1DUD2xJzuZZtslQOeo9V8Rw1c3FdlMg/5KvVGFlj0EvHSLFBmAmc2P9aTHuDqIm6kKO9zMVFxezyMSsNsnLdhoOKSU=```
در هر صورت من هنوز موفق به ارسال نشده ام

**Comment by thisiskarimi** [comment]
سلام و وقت بخیر
مربوط به احراز میباشد دقیقا به چه معنی هستش؟
یعنی در ساین کردن بسته مشکلی وجود داره؟

**Comment by hesamnn** [comment]
سلام وقت بخیر منم همین مشکل رو بعد از ارسال صورتحساب و وقتی میخوام استعلام بگیرم دارم 
یه سوال دیگه اینکه
sandboxrc برای شما کار میکنه ؟

**Comment by thisiskarimi** [comment]
سلام به شما. من تا حالا به سندباکس چیزی ارسال نکردم.

**Comment by nimbolism** [comment]
سلام 
سامانه سند باکس کار می کند حتی نسل جدید api که با همکاری مهیمن هست هم در اونجا کار می کنه
مشکل من هم در امضا صورتحساب بود
