### ISSUE TITLE
ارور در مرحله xor 

### ISSUE THREAD

**Issue by hesamnn** [thisiskarimi/moadian#3]
سلام و عرض ادب خدمت شما 
من موقع send invc به این ارور برمی خورم 

`Command 'php C:\Users\7Aseman-09\Desktop\7sky\venv\lib\site-packages\moadian_0\helper.php b709a278a1320641348523f824b4929abe824a244a45758a87a540560b66147e 0174748774530286ff52c752b5d534d7 '{"header": {"taxid": "A111220E1B9155CB1F18C7", "indatim": "20230910162652", "Indati2m": "20230910162652", "inty": "1", "inno": "0000011300", "irtaxid": null, "inp": "1", "ins": "1", "tins": "19117484910001", "tob": "1", "bid": "0", "tinb": "19117484910002", "sbc": "0", "bpc": "0", "bbc": "0", "ft": "0", "bpn": "0", "scln": "0", "scc": "0", "crn": "0", "billid": "0", "tprdis": "2400000", "tdis": "0", "tadis": "2400000", "tvam": "216000", "todam": "0", "tbill": "2616000", "setm": "1", "cap": "2616000", "insp": "0", "tvop": "216000", "tax17": "0"}, "body": [{"sstt": "\u0631\u0648\u063a\u0646 \u0628\u0647\u0631\u0627\u0646", "sstid": "1254219865985", "mu": "\u0644\u06cc\u062a\u0631", "am": "1", "fee": "2400000", "cfee": "0", "cut": "0", "exr": "0", "prdis": "2400000", "dis": "0", "adis": "2400000", "vra": "0.09", "vam": "216000", "odt": "0", "odr": "0", "odam": "0", "olt": "0", "olr": "0", "olam": "0", "consfee": "0", "spro": "0", "bros": "0", "tcpbs": "0", "cop": "0", "vop": "216000", "bsrn": null, "tsstam": "2616000"}], "payments": [{"iinn": "125036", "acn": "252544", "trmn": "2356566", "trn": "252545", "pcn": "6037991785693265", "pid": "19117484910002", "pdt": "1665490061447"}]}' ' returned non-zero exit status 1.`

تو قسمت لاگ هم 

`'php' is not recognized as an internal or external command,`

باتشکر از شما

**Comment by thisiskarimi** [comment]
سلام به شما.
مطمئن باشید که پی اچ پی به همراه ماژول openssl آن به درستی نصب شده باشد و کامند php یک کامند تعریف شده در سیستم باشد.

**Comment by hesamnn** [comment]
سلام آقا کریمی اگه مشکلی نیست یه شماره بده باهات تماس بگیرم فدات
